services:
    mysqldb:
        image: mysql:8.0
        container_name: mysqlcontainer
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
            - $HOME/database:/var/lib/mysql
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: dev_test
            MYSQL_USER: admin
            MYSQL_PASSWORD: my-secret-pw
            MYSQL_ROOT_PASSWORD: my-secret-pw
            SERVICE_TAGS: dev
            SERVICE_NAME: mysqldb
        networks:
            - internalnet

    nodeapp:
        container_name: nodeappcontainer
        build: ./server
        volumes:
            - ./server:/usr/app
        image: nodeapp:v1
        ports:
            - 5001:5001
        expose:
            - 5001
        environment:
            DB_HOSTNAME: mysqldb
            DB_PORT: 3306
            DB_USER: admin
            DB_PASSWORD: my-secret-pw
            DB_NAME: dev_test
            SERVICE_TAGS: dev
            SERVICE_NAME: nodeapp
            SERVER_PORT: 5001
        depends_on:
            - mysqldb
        networks:
            - internalnet
networks:
    internalnet:
        driver: bridge
